apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: calico-kube-controllers
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'secret'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  hostPorts:
  - min: 9091
    max: 9091
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: calico-node
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - CAP_SYS_ADMIN
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'hostPath'
    - 'secret'
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
  hostPorts:
  - min: 9091
    max: 9091
  allowedHostPaths:
  - pathPrefix: "/lib/modules"
  - pathPrefix: "/var/run/calico"
  - pathPrefix: "/var/lib/calico"
  - pathPrefix: "/run/xtables.lock"
  - pathPrefix: "/opt/cni/bin"
  - pathPrefix: "/etc/cni/net.d"
  - pathPrefix: "/var/lib/cni/networks"
  - pathPrefix: "/var/run/nodeagent"
  - pathPrefix: "{{ .Values.flexVolumePluginDir }}/nodeagent~uds"
  - pathPrefix: "/sys/fs"
  - pathPrefix: "/var/log/calico/cni"
  - pathPrefix: "/proc"
